/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.telas;

import com.mycompany.controller.Controller;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JPasswordField;

/**
 *
 * @author rafae
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botaoCadastrarUsuario = new javax.swing.JToggleButton();
        txtCadastroUsuario = new javax.swing.JFormattedTextField();
        txtCadastroEmail = new javax.swing.JFormattedTextField();
        txtCadastroSenha = new javax.swing.JPasswordField();
        txtCadastroCpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCadastroGenero = new javax.swing.JFormattedTextField();
        txtCadastroIdade = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de cadastro");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastre-se");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 19, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuário:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 78, 89, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 162, 49, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 249, 66, -1));

        botaoCadastrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCadastrarUsuario.setText("Cadastrar");
        botaoCadastrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 336, 135, -1));
        getContentPane().add(txtCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 104, 217, 32));
        getContentPane().add(txtCadastroEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 188, 217, 32));

        txtCadastroSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastroSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastroSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 275, 217, 32));
        getContentPane().add(txtCadastroCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 104, 217, 32));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CPF:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 78, 55, -1));
        getContentPane().add(txtCadastroGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 188, 217, 32));
        getContentPane().add(txtCadastroIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 275, 217, 32));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gênero:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 162, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Idade:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 249, 52, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton1.setText("Voltar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 336, 135, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCadastroSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastroSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastroSenhaActionPerformed

    private void botaoCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarUsuarioActionPerformed
    
       try {
           Controller cadastro = new Controller();
            cadastro.cadastroUsuario(this);
       } catch(SQLException sql){
           
       }
        this.setVisible(false);
    }//GEN-LAST:event_botaoCadastrarUsuarioActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
            TelaLogin TelaLogin = new TelaLogin();
            TelaLogin.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    public JFormattedTextField getTxtCadastroEmail() {
        return txtCadastroEmail;
    }

    public void setTxtCadastroEmail(JFormattedTextField txtCadastroEmail) {
        this.txtCadastroEmail = txtCadastroEmail;
    }

    public JPasswordField getTxtCadastroSenha() {
        return txtCadastroSenha;
    }

    public void setTxtCadastroSenha(JPasswordField txtCadastroSenha) {
        this.txtCadastroSenha = txtCadastroSenha;
    }

    public JFormattedTextField getTxtCadastroUsuario() {
        return txtCadastroUsuario;
    }

    public void setTxtCadastroUsuario(JFormattedTextField txtCadastroUsuario) {
        this.txtCadastroUsuario = txtCadastroUsuario;
    }
    public JFormattedTextField getTxtCadastroCpf() {
        return txtCadastroCpf;
    }

    public void setTxtCadastroCpf(JFormattedTextField txtCadastroEmail) {
        this.txtCadastroCpf = txtCadastroCpf;
    }

    public JFormattedTextField getTxtCadastroGenero() {
        return txtCadastroGenero;
    }

    public void setTxtCadastroGenero(JPasswordField txtCadastroSenha) {
        this.txtCadastroGenero = txtCadastroGenero;
    }

    public JFormattedTextField getTxtCadastroIdade() {
        return txtCadastroIdade;
    }

    public void setTxtCadastroIdade(JFormattedTextField txtCadastroUsuario) {
        this.txtCadastroIdade = txtCadastroIdade;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoCadastrarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JFormattedTextField txtCadastroCpf;
    private javax.swing.JFormattedTextField txtCadastroEmail;
    private javax.swing.JFormattedTextField txtCadastroGenero;
    private javax.swing.JFormattedTextField txtCadastroIdade;
    private javax.swing.JPasswordField txtCadastroSenha;
    private javax.swing.JFormattedTextField txtCadastroUsuario;
    // End of variables declaration//GEN-END:variables

    public Object gettxtCadastroUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object getpassawordTxtCadastroSenha() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   
}
