/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.telas;

import com.mycompany.controller.Controller;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author rafae
 */
public class TelaCadastroEvento extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroEvento
     */
    public TelaCadastroEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCadastroHorario_termino = new javax.swing.JFormattedTextField();
        txtCadastroHorario_inicio = new javax.swing.JFormattedTextField();
        botaoCadastrarEvento = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCadastroData_evento = new javax.swing.JFormattedTextField();
        txtCadastroEmpresa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCadastroDesc_evento = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de eventos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de evento:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 19, -1, -1));

        txtCadastroHorario_termino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastroHorario_terminoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastroHorario_termino, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 284, 217, 32));
        getContentPane().add(txtCadastroHorario_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 217, 32));

        botaoCadastrarEvento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoCadastrarEvento.setText("Cadastrar");
        botaoCadastrarEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCadastrarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarEventoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastrarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 334, 135, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Empresa:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 78, 66, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descrição do evento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 154, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Horário de início:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Horário de término:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 252, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 78, 37, -1));
        getContentPane().add(txtCadastroData_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 110, 217, 32));

        txtCadastroEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastroEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCadastroEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 217, 32));

        txtCadastroDesc_evento.setColumns(20);
        txtCadastroDesc_evento.setLineWrap(true);
        txtCadastroDesc_evento.setRows(5);
        txtCadastroDesc_evento.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtCadastroDesc_evento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 180, 217, 136));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton2.setText("Voltar");
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 334, 135, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarEventoActionPerformed
 
        try {
            Controller cadastro = new Controller();
            cadastro.cadastroEvento(this);
            TelaInicial TelaInicial = new TelaInicial();
            TelaInicial.setVisible(true);
            TelaInicial.menuCadEventos.setEnabled(true);
            this.dispose();
        } catch (SQLException sql) {
           
        }
        this.setVisible(false);
    }//GEN-LAST:event_botaoCadastrarEventoActionPerformed

    private void txtCadastroHorario_terminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastroHorario_terminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastroHorario_terminoActionPerformed

    private void txtCadastroEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastroEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastroEmpresaActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
            TelaInicial TelaInicial = new TelaInicial();
            TelaInicial.setVisible(true);
            TelaInicial.menuCadEventos.setEnabled(true);
            this.dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed
    
    public JTextField getTxtCadastroEmpresa() {
        return txtCadastroEmpresa;
    }

    public void setTxtCadastroEmpresa(JFormattedTextField txtCadastroEmail) {
        this.txtCadastroEmpresa = txtCadastroEmpresa;
    }

    public JFormattedTextField getTxtCadastroData_evento() {
        return txtCadastroData_evento;
    }
    
    public void setTxtCadastroData_evento(JFormattedTextField txtCadastroUsuario) {
        this.txtCadastroData_evento = txtCadastroData_evento;
    }
    
    public JFormattedTextField getTxtCadastroHorario_termino() {
        return txtCadastroHorario_termino;
    }

    public void setTxtCadastroHorario_termino(JFormattedTextField txtCadastroUsuario) {
        this.txtCadastroHorario_termino = txtCadastroHorario_termino;
    }
     
    public JTextArea getTxtCadastroDesc_evento() {
        return txtCadastroDesc_evento;
    }
     
    public void setTxtCadastroDesc_evento(JFormattedTextField txtCadastroUsuario) {
        this.txtCadastroDesc_evento = txtCadastroDesc_evento;
    }
    
    public JFormattedTextField getTxtCadastroHorario_inicio() {
        return txtCadastroHorario_inicio;
    }

    public void setTxtCadastroHorario_inicio(JFormattedTextField txtCadastroUsuario) {
        this.txtCadastroHorario_inicio = txtCadastroHorario_inicio;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoCadastrarEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JFormattedTextField txtCadastroData_evento;
    private javax.swing.JTextArea txtCadastroDesc_evento;
    private javax.swing.JTextField txtCadastroEmpresa;
    private javax.swing.JFormattedTextField txtCadastroHorario_inicio;
    private javax.swing.JFormattedTextField txtCadastroHorario_termino;
    // End of variables declaration//GEN-END:variables

    
    void SetVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


}
